// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbGCyaycjobm4feGKdi_IYzI0eC5rOfM',
    appId: '1:242159102479:web:6f8e5f25fe6c659343117a',
    messagingSenderId: '242159102479',
    projectId: 'community-challenge-app',
    authDomain: 'community-challenge-app.firebaseapp.com',
    storageBucket: 'community-challenge-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2X-9BXsazfKUV-_vmla2iNN-Rc6kFH8',
    appId: '1:242159102479:android:5fd28e5e173be43043117a',
    messagingSenderId: '242159102479',
    projectId: 'community-challenge-app',
    storageBucket: 'community-challenge-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-1X7Betfo9DH1oaYTBEAUDPuGEA196M',
    appId: '1:242159102479:ios:dd918e85c7d3382a43117a',
    messagingSenderId: '242159102479',
    projectId: 'community-challenge-app',
    storageBucket: 'community-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.communityChallengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-1X7Betfo9DH1oaYTBEAUDPuGEA196M',
    appId: '1:242159102479:ios:dd918e85c7d3382a43117a',
    messagingSenderId: '242159102479',
    projectId: 'community-challenge-app',
    storageBucket: 'community-challenge-app.firebasestorage.app',
    iosBundleId: 'com.example.communityChallengeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhbGCyaycjobm4feGKdi_IYzI0eC5rOfM',
    appId: '1:242159102479:web:96499e6ad53cb25943117a',
    messagingSenderId: '242159102479',
    projectId: 'community-challenge-app',
    authDomain: 'community-challenge-app.firebaseapp.com',
    storageBucket: 'community-challenge-app.firebasestorage.app',
  );
}
